Repository shopware/sw-sync-cli, pull requests merged in 2024-08, with the labels that each got.

#18 NEXT-37504 - fix nested associations
  .gitignore
  CHANGELOG.md
  src/api/filter.rs
  src/api/mod.rs
  src/data/export.rs
Labels: bug

#24 Delete old coverage comments from pr
  .github/workflows/ci.yml
Labels: bug

#26 Fix ci workflow
  .github/workflows/ci.yml
Labels: bug

#25 Compare coverage of main and pr branch
  .github/scripts/comment-coverage.js
  .github/scripts/main-coverage.js
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: enhancement

#22 NEXT-37317 - create default profiles
  CHANGELOG.md
  profiles/default_advanced_price.yaml
  profiles/default_cross_selling.yaml
  profiles/default_customer.yaml
  profiles/default_media.yaml
  profiles/default_newsletter_recipient.yaml
  profiles/default_order.yaml
  profiles/default_product.yaml
  profiles/default_product_variants.yaml
  profiles/default_promotion_code.yaml
  profiles/default_promotion_discount.yaml
  profiles/default_property.yaml
  profiles/default_variant_configuration.yaml
  profiles/manufacturer.yaml
  profiles/product_required.yaml
  profiles/product_variants.yaml
  profiles/product_with_manufacturer.yaml
  src/config_file.rs
  src/data/export.rs
Labels: bug, enhancement

#21 NEXT-37303 - Refactor away from async
  Cargo.lock
  Cargo.toml
  src/api/mod.rs
  src/cli.rs
  src/config_file.rs
  src/data/export.rs
  src/data/import.rs
  src/main.rs
Labels: enhancement

#17 NEXT-37313 - api client reauthentication
  CHANGELOG.md
  src/api/mod.rs
Labels: enhancement

#33 NEXT-37516 - Changed import error handling for database deadlock error
  CHANGELOG.md
  src/api/mod.rs
  src/cli.rs
  src/data/import.rs
  src/main.rs
Labels: bug, enhancement

#34 Next 37781 - Fix quotes from scripts + prepare v0.8.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  profiles/default_product.yaml
  src/data/transform/mod.rs
Labels: bug

#32 NEXT-37303 - Increase coverage by testing API calls
  Cargo.lock
  Cargo.toml
  src/api/mod.rs
Labels: enhancement
